permalink: :year/:month/:day/:title
markdown: kramdown
highlighter: rouge
date_format: "ordinal"
subscribe_rss: /atom.xml
gems: [jekyll-paginate]

markdown: kramdown
kramdown:
    input:  GFM
    syntax_highlighter: rouge

